### ISSUE TITLE
[Fatal Error Report] Pro version fatal error

### ISSUE THREAD

**Issue by michaeledi** [raphcadiz/gravity2pdf#1] opened 2016-11-14 01:47 UTC
Hi, 
I have bought your pro version, but it seems not working at all. 
First I tried the v2.0, but it cannot even be activated, and here is the error code on wordpress:

> Plugin could not be activated because it triggered a fatal error.
> Fatal error: 'continue' not in the 'loop' or 'switch' context in /data/wwwroot/ff3dm.com/wp-content/plugins/Gravity2PDF/class/gravity_merge_send.class.php on line 191

And then I turned to use the v1.0.3, and it still have problem, the TK library needs CentOS 5 or 6 but mine is 7, so I tried to select "use our library", but then it shows the temp path is required, which shouldn't appear in this choice. But I did write a path, and it doesn't work either.

I don't understand why a paid version could have more problems than the free version, and you guys even don't have a support email displayed in your website, that's not a proper attitude for selling a software.

I hope this issue can be resolved, or I have to refund the money, even I cannot find where and how to do that either...
Regards,
Edi

**Comment by raphcadiz** [comment] 2016-11-14 02:36
Hi @michaeledi what PHP version are you using? This plugin works on PHP 5.6.*

**Comment by michaeledi** [comment] 2016-11-14 02:37
@raphcadiz I'm using PHP7, so there is no way I can use this plugin?

**Comment by raphcadiz** [comment] 2016-11-14 02:43
@michaeledi should work on PHP 7 also. I'll try to check on the issue and get back to you. Did you bought the plugin in here https://www.gravity2pdf.com/ ?

**Comment by michaeledi** [comment] 2016-11-14 02:45
@raphcadiz Yes, and I have tried 2 paid version, both invalid.

**Comment by raphcadiz** [comment] 2016-11-14 02:45
Ok, We will check on this issue and get back to you.

**Comment by michaeledi** [comment] 2016-11-14 02:52
@raphcadiz okay, I will be waiting online.

**Comment by raphcadiz** [comment] 2016-11-14 03:07
@michaeledi I need your email address you used to purchased the plugin, somebody will contact you directly.

**Comment by michaeledi** [comment] 2016-11-14 03:14
@raphcadiz 3d@ff3dm.com

**Comment by raphcadiz** [comment] 2016-11-14 03:21
Try to download the latest version of the plugin. And may I know the current environment you are running the plugin. Wp version, PHP, server  etc.

**Comment by michaeledi** [comment] 2016-11-14 03:25
I have downloaded the latest from the account page, didn't work.
WP: 4.6.1
PHP: 7
CentOS 7

**Comment by raphcadiz** [comment] 2016-11-14 03:46
@michaeledi It turns out that the issue is on PHP 7. I just made the fix and uploaded the plugin. Please download it again and let me know if it fixed it.

**Comment by michaeledi** [comment] 2016-11-14 03:51
Ok, thanks, I will try it.

**Comment by raphcadiz** [comment] 2016-11-14 04:19
I'm closing this issue.

**Closed by raphcadiz** 2016-11-14 04:19 UTC

**Comment by michaeledi** [comment] 2016-11-14 05:08
Ok, it works, thanks for the instant support!
